### ISSUE TITLE
[BUG] - Update Compare application, dependencies, and webpack configuration

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/BackstopJS#38]
# Requirements

Currently `npm run build-compare` fails due to webpack/babel configuration conflicts. This may be due to differences in how Node handles blobs in > 14.x.x.

# Possible Solutions

- see https://github.com/dgrebb/dg-backstop/commit/aa47497ae32a40f78bac16f7ad8b47fae769e196 for a starting point

# Details

```bash
❯ npm run build-compare

> backstopjs@6.2.2 build-compare
> cp ./node_modules/diverged/src/diverged.js ./compare/output/ && cp ./node_modules/diff/dist/diff.js ./compare/output/ && webpack --config ./compare/webpack.config.js && npm run lint

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Plugin/Preset files are not allowed to export objects, only functions. In /BackstopJS/node_modules/babel-preset-es2015/lib/index.js
    at createDescriptor (/BackstopJS/node_modules/@babel/core/lib/config/config-descriptors.js:159:11)
    at createDescriptor.next (<anonymous>)
    at step (/BackstopJS/node_modules/gensync/index.js:261:32)
    at /BackstopJS/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/BackstopJS/node_modules/gensync/index.js:223:11)

Node.js v20.8.1
```

**Comment by dgrebb** [comment]
Closed by https://github.com/garris/BackstopJS/pull/1532
